fix wasi ci testing and update doc in README (#367)
* Speedup exhaustive.yml

Do not run cargo-hack on all crates, since codecs features are subset of async-compression features

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* ci: speedup clippy in lint.yml

Do not run clippy on dependencies

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* ci: speedup clippy in nightly.yml

Do not run clippy on dependencies

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Use latest wasi sysroot in wasi.yml

And use cargo-check instead of cargo-build

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Update README.md for wasi testing

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Speedup cargo-hack in exhaustive.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Fix exhaustive.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Speedup exhaustive.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Fix exhaustive.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Fix exhaustive.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Speedup exhaustive.yml

Limit powerser depth to 4


Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

* Fix wasi.yml

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

---------

Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

diff --git a/.github/workflows/exhaustive.yml b/.github/workflows/exhaustive.yml
--- a/.github/workflows/exhaustive.yml
+++ b/.github/workflows/exhaustive.yml
@@ -73,7 +73,10 @@ jobs:
     - run: cargo --locked test --workspace --doc --all-features
 
   check-features:
-    name: cargo hack check --feature-powerset
+    strategy:
+      matrix:
+        async_runtime: [tokio, futures-io]
+    name: cargo hack check --feature-powerset --features ${{ matrix.async_runtime }}
     runs-on: ubuntu-latest
     env:
       RUSTFLAGS: -Dwarnings
@@ -82,15 +85,23 @@ jobs:
     - uses: actions-rust-lang/setup-rust-toolchain@v1
     - uses: taiki-e/install-action@v2
       with: { tool: cargo-hack }
-    - run:
-        cargo hack check
-          --workspace
-          --feature-powerset
-          --no-dev-deps
-          --skip 'all,all-algorithms,all-implementations'
+    - name: cargo-hack check
+      run: |
+        set -exuo pipefail
+        skipped_features=$(echo 'futures-io,tokio,' | sed 's/${{ matrix.async_runtime }},//')
+        cargo hack check \
+          --feature-powerset \
+          --features ${{ matrix.async_runtime }} \
+          --no-dev-deps \
+          --skip "all,all-algorithms,${skipped_features}all-implementations,xz-parallel,zstdmt" \
+          --depth 4
+        cargo check --features ${{ matrix.async_runtime }},xz-parallel,zstdmt
 
   check-test-features:
-    name: cargo hack check --all-targets --feature-powerset
+    strategy:
+      matrix:
+        async_runtime: [tokio, futures-io]
+    name: cargo check --all-targets --feature-powerset --features ${{ matrix.async_runtime }}
     runs-on: ubuntu-latest
     env:
       RUSTFLAGS: -Dwarnings
@@ -99,12 +110,34 @@ jobs:
     - uses: actions-rust-lang/setup-rust-toolchain@v1
     - uses: taiki-e/install-action@v2
       with: { tool: cargo-hack }
-    - run:
-        cargo hack check
-          --workspace
-          --feature-powerset
-          --all-targets
-          --skip 'all,all-algorithms,all-implementations'
+    - name: cargo-hack check
+      run: |
+        set -exuo pipefail
+        skipped_features=$(echo 'futures-io,tokio,' | sed 's/${{ matrix.async_runtime }},//')
+        cargo hack check \
+          --feature-powerset \
+          --features ${{ matrix.async_runtime }} \
+          --all-targets \
+          --skip "all,all-algorithms,${skipped_features}all-implementations,xz-parallel,zstdmt" \
+          --depth 4
+        cargo check --all-targets --features ${{ matrix.async_runtime }},xz-parallel,zstdmt
+
+  # Dummy job to have a stable name for the "all tests pass" requirement
+  tests-pass:
+    name: Exhaustive tests pass
+    needs:
+      - test
+      - min-versions-shallow
+      - min-versions
+      - check-features
+      - check-test-features
+    if: always() # always run even if dependencies fail
+    runs-on: ubuntu-latest
+    steps:
+      # fail if ANY dependency has failed or cancelled
+      - if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
+        run: exit 1
+      - run: exit 0
 
 on:
   merge_group:
